# Site settings
title: A blog about myself
description: A blog about myself
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Justin Tan
user_description: Undergraduate in NUS, Computer Engineering.
user_title: Software Developer
email: justintankunjie@gmail.com
twitter_username: lorem_ipsum
github_username:  justintkj
gplus_username:  justintkj
baseurl: "/JUSTIN-RESUME" # the subpath of your site, e.g. /blog
# Google-analytics
google-analytics:
  id: ""
  
plugins:
  - jekyll-seo-tag
  
exclude: ['package.json', 'src' , 'node_modules']
